from typing import List, Optional
from sqlmodel import Field, Relationship, Session, SQLModel, create_engine


class DeviceTagLink(SQLModel, table=True):
    tag_id: Optional[int] = Field(default=None, foreign_key="tag.id", primary_key=True)
    device_id: Optional[int] = Field(default=None, foreign_key="device.id", primary_key=True)

# generated by datamodel-codegen:
#   filename:  schemas/timestamped-record.schema.json
class TimestampedRecord(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    record: str = Field(..., description='serialized JSON (from any type in schema)')
    timestampSeconds: float

    device_id: Optional[int] = Field(default=None, foreign_key="device.id")
    versionedSchema_id: Optional[int] = Field(default=None, foreign_key="versionedschema.id")

# generated by datamodel-codegen:
#   filename:  schemas/device.schema.json
class Device(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    properties: Optional[str] = Field(
        None, description='serialized JSON (from any type in schema)'
    )

    tags: List["Tag"] = Relationship(back_populates="devices", link_model=DeviceTagLink)

# generated by datamodel-codegen:
#   filename:  schemas/versioned-schema.schema.json
class VersionedSchema(SQLModel, table=True):
    content: str
    id: Optional[int] = Field(default=None, primary_key=True)
    parents: Optional[str] = Field(
        None, description='serialized JSON (from any type in schema)'
    )
    sha256: Optional[str] = None
    transformerCode: Optional[str] = None



# generated by datamodel-codegen:
#   filename:  schemas/tag.schema.json
class Tag(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    text: str

    devices: List["Device"] = Relationship(back_populates="tags", link_model=DeviceTagLink)
